#!/bin/sh
# 時間単位天気予報のスクリプト(色付き、各国語対応)

# 場所のURL（日本語表記にしたい場合は/en/を/ja/に書き換える）
weather_url="https://www.accuweather.com/en/jp/koto-ku/221230/weather-forecast/221230"

# AMとPMの色  30 黒、31 赤、32 緑、33 黄、34 青、35 マゼンタ、36 シアン、37 白、0 デフォルト
AM_COLOR=31
PM_COLOR=34

# 何時間分？
hour=24
[ $# -ne 0 ] && hour=$1

# 何時間後？ (時間をずらしたい場合はlaterの後の数字を書き換える)
later=0
[ $# -eq 2 ] && later=$2

# 元データ取得
user_agent="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X)"
weather_data0=`curl -H "$user_agent" --silent ${weather_url/weather-forecast/hourly-weather-forecast}`
weather_data1=`curl -H "$user_agent" --silent ${weather_url/weather-forecast/hourly-weather-forecast}"?day=1"`
hour_data=$(echo "$weather_data0" "$weather_data1" | grep 'hourlyForecast' | tr '{|}' '\n' | grep 'localTime' | sed -n $(expr 1 + $later),$(expr $hour + $later)p)
locale_data=$(echo "$weather_data0" | grep -e 'pageLocale' |  tr '{|}' '\n' | sed s/',"'/\\$'\n'/g | tr -d '"')
locale_precip=$(echo "$locale_data" | grep -m1 'precip:' | awk -F: '{print $2}')

# 指定された時間分の時刻を取得（後で配列変数として使う。以下同様）
_IFS="$IFS";IFS="
"
current_time=(`echo "$hour_data" | awk -F'"localTime":' '{print $2}' | cut -d"\"" -f2 | cut -d"\"" -f1`) 
IFS="$_IFS"

# 指定された時間分のデータを取得
_IFS="$IFS";IFS="
"
current_temp=(`echo "$hour_data" | awk -F'"temp":' '{print $2}' | cut -d"\"" -f2 | cut -d"\"" -f1`) 
current_precip=(`echo "$hour_data" | awk -F'"precip":' '{print $2}' | cut -d"\"" -f2 | cut -d"\"" -f1`) 
current_weather=(`echo "$hour_data" | awk -F'"phrase":' '{print $2}' | cut -d"\"" -f2 | cut -d"\"" -f1`) 
IFS="$_IFS"

# 時刻と天気を表示
_IFS="$IFS";IFS="
"
for (( i=0; i < ${#current_time[@]}; ++i))
do
if [ "`echo $weather_url | grep '/hi/\|/ar/\|/el/\|/ko/\|/ms/\|/bn/\|/ur/\|/kn/\|/te/\|/mr/\|/pa/\|/zh\|/en/'`" ]; then
printf "%5s  " "${current_time[$i]}" | sed -E 's/AM|पूर्वाह्न|π.μ.|오전|PG|পূর্বাহ্|ಪೂರ್ವಾಹ್ನ|म.पू.|ਪੂ.ਦੁ.|上午|ص|قبل دوپہر/'`printf "\033[0;${AM_COLOR}m"`'&'`printf "\033[0m"`'/' | sed -E 's/PM|अपराह्|μ.μ.|오후|PTG|অপরাহ্ণ|ಅಪರಾಹ್ನ|PM|म.उ.|ਬਾ.ਦੁ.|下午|م|بعد دوپہر/'`printf "\033[0;${PM_COLOR}m"`'&'`printf "\033[0m"`'/' | tr -d '\n'
else
printf "%5s  " "${current_time[$i]}" | perl -pe 's/((?<![0-9])([0-9])(?![0-9])|0[0-9]|1[0-1])/\1'`printf "\033[0;${AM_COLOR}m"`'/' | sed -E 's/(1[2-9]|2[0-3])/&'`printf "\033[0;${PM_COLOR}m"`'/' | sed -E 's/$/'`printf "\033[0m"`'/' | tr -d '\n'
fi
echo "${current_temp[$i]} ${locale_precip}:$(printf "%4s" "${current_precip[$i]}")  ${current_weather[$i]}"
done
IFS="$_IFS"
