#!/bin/bash
# 現在の天気のスクリプト

# 場所のURL（日本語表記にしたい場合は/en/を/ja/に書き換える）
WEATHER_URL=${WEATHER_URL:='MY_WEATHER_URL'}

# 見出しと天気とMINUTECASTの色（30 黒、31 赤、32 緑、33 黄、34 青、35 マゼンタ、36 シアン、37 白、0 デフォルト、1 強調、2 弱強調、4 下線、5 点滅、7 反転）
COLOR_CP='1'  # 見出し
COLOR_WE='0'  # 天気
COLOR_MC='1'  # MINUITECAST
COLOR_WN='31' # 気象警報

# 使い方
function usage() {
cat <<_EOT_
使い方:
  ${0##*/} [-c | -d | -n | -t | -h] [-l 言語]

説明:
  現在の天気予報

オプション:
  -c    現在の天気を表示       （Current）
  -d    日中の天気を表示       （Day）
  -n    夜間の天気を表示       （Night）
  -t    明日の天気を表示       （Tomorrow）
  -h    ヘルプ
  -l    表示言語
        （ja:日本語、en:English、fr:Français、de:Deutsch、zh-cn:中文 (SIM)など）

_EOT_
exit 1
}

# 引数の設定
while getopts scdnthl: OPT
do
  case $OPT in
    c) FLG_C='true' ;;
    d) FLG_D='true' ;;
    n) FLG_N='true' ;;
    t) FLG_T='true' ;;
    h) usage; exit 1 ;;
    l) LN=$(echo $WEATHER_URL | awk -F'www.accuweather.com' '{print $2}' | awk -F/ '{print $2}')
       WEATHER_URL=${WEATHER_URL/\/$LN\//\/"$OPTARG"\/} ;;
    *) usage; exit 1 ;;
  esac
done

if [ "$FLG_C" != 'true' ] && [ "$FLG_D" != 'true' ] && [ "$FLG_N" != 'true' ] && [ "$FLG_T" != 'true' ]; then
  FLG_C='true'; FLG_D='true'; FLG_N='true'; FLG_T='true'
fi

# データ整理用関数
pickup_data() { echo "$1" | grep -m1 $2 | tr '{|}' '\n' | perl -pe 's/,"/\n/g' | tr -d '"'; }

# 元データ取得
USER_AGENT='Mozilla/5.0 (Macintosh; Intel Mac OS X)'
WEATHER_DATA=$(curl -A "$USER_AGENT" --silent $WEATHER_URL)
WEATHER_HOUR=$(curl -A "$USER_AGENT" --silent ${WEATHER_URL/weather-forecast/hourly-weather-forecast})
DATA_NOW="$(echo "$WEATHER_DATA" | awk '/a class="panel panel-fade-in card current "/,/threeday-panel-next/' | tr -d '\t' | ruby -pe 'gsub(/&#[xX]([0-9a-fA-F]+);/) { [$1.to_i(16)].pack("U") }')"
DATA_MC=$(echo "$WEATHER_DATA" | grep -A5 '<div class="banner-header">' | tr -d '\t' | ruby -pe 'gsub(/&#[xX]([0-9a-fA-F]+);/) { [$1.to_i(16)].pack("U") }')
DATA_WN=$(echo "$WEATHER_DATA" | grep -A3 '<div class="alert-banner alert-banner-weather">' | grep '<span>' | sed 's/<[^>]*>//g' | tr -d '\t' | ruby -pe 'gsub(/&#[xX]([0-9a-fA-F]+);/) { [$1.to_i(16)].pack("U") }')

# 各データ取得
_IFS="$IFS";IFS=$'\n'
TITLE=($(echo "$DATA_NOW" | grep -A1 '<p class="module-header">' | grep -v '<p class="module-header">' | perl -pe 's/--\n//g'))
TEMP_HI=($(echo "$DATA_NOW" | grep -A1 '<span class="high">' | grep -v '<span class="high">' | perl -pe 's/--\n//g'))
TEMP_LO=($(echo "$DATA_NOW" | grep -A1 '<span class="low">' | grep -v '<span class="low">' | perl -pe 's/--\n//g'))
PHRASE=($(echo "$DATA_NOW" | grep -A1 '<div class="cond">' | grep -v '<div class="cond">' | perl -pe 's/--\n//g'))
IFS="$_IFS"

# 現在の温度と天気を取得
if [ "$FLG_C" = 'true' ]; then
  COLUMN="$(echo -e -n "\033[${COLOR_CP}m"$(echo "${TITLE[0]}")"\033[0m:")""@"
  COLUMN="${COLUMN}$(echo -e $(echo ${TEMP_HI[0]}${TEMP_LO[0]})@"\033[${COLOR_WE}m"$(echo ${PHRASE[0]})"\033[0m")""\n"
fi
# 日中の最高気温、天気を取得
if [ "$FLG_D" = 'true' ]; then
  COLUMN="${COLUMN}$(echo -e -n "\033[${COLOR_CP}m""$(echo "${TITLE[1]}")""\033[0m: ")""@"
  COLUMN="${COLUMN}$(echo -e $(echo ${TEMP_HI[1]}${TEMP_LO[1]})@"\033[${COLOR_WE}m"$(echo ${PHRASE[1]})"\033[0m")""\n"
fi
# 夜間の最低気温、天気を取得
if [ "$FLG_N" = 'true' ]; then
  COLUMN="${COLUMN}$(echo -e -n "\033[${COLOR_CP}m""$(echo "${TITLE[2]}")""\033[0m: ")""@"
  COLUMN="${COLUMN}$(echo -e $(echo ${TEMP_HI[2]}${TEMP_LO[2]})@"\033[${COLOR_WE}m"$(echo ${PHRASE[2]})"\033[0m")""\n"
fi
# 明日の最高・最低気温、天気を取得
if [ "$FLG_T" = 'true' ]; then
  COLUMN="${COLUMN}$(echo -e -n "\033[${COLOR_CP}m""$(echo "${TITLE[3]}")""\033[0m: ")""@"
  COLUMN="${COLUMN}$(echo -e $(echo ${TEMP_HI[3]}${TEMP_LO[3]})@"\033[${COLOR_WE}m"$(echo ${PHRASE[3]})"\033[0m")""\n"
fi

# 地名を表示
PLACE=($(pickup_data "$WEATHER_DATA" 'currentLocation' | grep localizedName | awk -F: '{print $2}'))
echo ${PLACE[2]}, ${PLACE[0]}
# 各データを表として表示
echo -e "$COLUMN" | column -t -s"@"

# MINUTECASTを表示
if [ "`echo "$WEATHER_DATA" | grep '<div class="banner-header">'`" ]; then
TITLE=$(echo "$DATA_MC" | grep -A1 '<div class="banner-header">' | sed -n 2p)
PHRASE=$(echo "$DATA_MC" | grep -A1 '<div class="banner-text">' | sed -n 2p)
echo $(printf "\033[0;${COLOR_MC}m")"$TITLE:$(printf "\033[0m") $PHRASE"
fi
# Warningを表示
if [ "`echo "$WEATHER_DATA" | grep '<div class="alert-banner alert-banner-weather">'`" ]; then
echo "$DATA_WN" | sed -E 's/^/'$(printf "\033[0;${COLOR_WN}m")'/' | sed -E 's/$/'$(printf "\033[0m")'/'
fi
